DROP DATABASE IF EXISTS burgers_db;

CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE burgers (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR (255) NOT NULL,
    is_eaten BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(id)
)